PYTHON VS NUMPY, lets check the speed of both!

In [1]:
l = range (100000)


In [2]:
import numpy as np

In [3]:
#  range in Python ===>  generates list
#  arange in Numpy ====> generates list.
#  Numpy performs actions 100 times faster than Python and other libraries. 
#  Python libraries use Numpy as a base for Data exchange. Often called 'Lingua Franca for Python libraries'

In [4]:
d = np.arange(100000)

In [5]:
%time for i in range (1,10):  [x*2 for x in l]  #x is a number *2 from l           #total: 117 ms

CPU times: user 108 ms, sys: 12 ms, total: 120 ms
Wall time: 119 ms


In [6]:
%time for i in range (1,10): r = d*2                                              #total: 9.61 ms

CPU times: user 6.59 ms, sys: 263 µs, total: 6.85 ms
Wall time: 5.91 ms


# ndArray

In [7]:
#  fast, flexible containers for large data sets in Pyton.
# Homogeneous data i.e all elements must be of same type.
#  size of the arrray determined by tupple.

In [8]:
x = np.zeros ((4,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
y = np.ones ((6,6))
y

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
np.empty ((7,7))                  #creates array for zeros in a 7 by 7 order.


array([[2.08804617e-115, 6.46572285e+170, 1.10633865e+200,
        1.05604052e+267, 4.51634594e+217, 1.05019735e-153,
        5.82471374e+257],
       [1.69593624e-152, 9.35319239e+252, 5.75680933e+252,
        2.37269831e+267, 6.01346953e-154, 4.70107982e+180,
        7.20185273e+159],
       [8.82893671e+199, 6.01346953e-154, 1.33360291e+241,
        1.53584743e-253, 2.64089007e-313, 2.98233776e-308,
        1.33360296e+241],
       [8.39037136e-311, 3.22635710e-307, 2.03016870e-316,
        4.16865225e+199, 1.43762582e+217, 4.61249234e-303,
        3.10362194e+175],
       [1.05335199e+277, 3.81291163e+180, 1.71387267e+214,
        4.79129674e-309, 5.80220124e+180, 2.12369026e+127,
        4.24297177e+228],
       [7.80002581e-271, 8.36775750e+242, 2.95806213e-311,
        5.03961303e-266, 2.56930068e+151, 6.19634321e+223,
        6.79153007e+199],
       [3.38460686e+125, 2.29046322e+159, 3.06567261e-313,
        2.00886795e-308, 3.38460675e+125, 3.69028917e+180,
        3.12194811

In [12]:
a = [1,2,3,4]
np.array (a)

array([1, 2, 3, 4])

In [19]:
b =np.arange (1,100,10)                               #how arrays created

In [20]:
b.shape                    #FOR SHAPE POF ARRAY        One dimensional array with 10 elements.

(10,)

In [24]:
x = np.zeros ((10,10))

In [26]:
x.shape

(10, 10)

In [29]:
y = x.reshape ((2,2,5,5))                             #reshaped.

In [30]:
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [31]:
y.dtype              #datatype checked


dtype('float64')

# Arthematics with ndArray

In [32]:
# String data can also be stored in Numpy.

In [33]:
# Array oriented  operations are performed in Numpy.
#  Also called two arrays.
# Any scalar required to be multiplied by any Vector - this operation can also be performed.

In [34]:
a = np.random.randn((10))

In [35]:
b = np.random.randn((10))

In [36]:
a

array([-1.43187265, -1.01860914,  0.9132669 , -0.48859637,  0.95507277,
        0.31775242,  0.03691037, -0.09084431,  0.52470983, -0.19341456])

In [37]:
b

array([-1.69453138,  1.28468258, -0.05848149, -1.21031418, -1.27691276,
       -1.07864776,  0.66641819, -0.15593879, -1.38001258, -0.23192756])

In [38]:
a+b

array([-3.12640403,  0.26607344,  0.8547854 , -1.69891055, -0.32183999,
       -0.76089534,  0.70332855, -0.2467831 , -0.85530275, -0.42534212])

In [39]:
#  Numpy arrays can be added, subtracted or multiplied in Numpy but this operation couldn't be performed in a List.

In [40]:
a-b

array([ 0.26265872, -2.30329172,  0.97174839,  0.7217178 ,  2.23198553,
        1.39640018, -0.62950782,  0.06509448,  1.90472242,  0.03851299])

In [42]:
a>0           #boolean array generated.

array([False, False,  True, False,  True,  True,  True, False,  True,
       False])

In [44]:
a[a>0]                  #a packed hence only True elements picked and given in output.

array([0.9132669 , 0.95507277, 0.31775242, 0.03691037, 0.52470983])

# Indexing and Slicing

In [46]:
#  Position specified and indexing and slicing done.
# Fancy indexing can also be done.   ==> Calling elements by means of only mentioning the indexes specified.

In [53]:
x = np.array ([1,7,9,8,5])

In [54]:
x[4]

5

In [55]:
x>5

array([False,  True,  True,  True, False])

In [56]:
x[x>5]

array([7, 9, 8])

In [58]:
x[[2,1]]

array([9, 7])

In [59]:
a = np.random.randn(10,10)
a

array([[ 4.42028637e-01, -5.27804473e-01, -3.06399957e-03,
         7.80575854e-01, -3.11549342e-01,  5.14199915e-01,
        -1.24004498e+00, -6.15404361e-01, -9.28805527e-01,
         5.92363942e-01],
       [-1.09038052e+00,  1.87959939e+00, -7.67472696e-01,
         6.15149730e-01, -3.17863925e-01,  6.27447121e-02,
        -4.55060570e-02, -3.64206183e-01,  9.66977879e-01,
        -4.78232272e-01],
       [ 8.89453723e-01, -1.82821974e+00, -8.43331895e-01,
         1.26001740e+00,  3.87759008e-01, -5.61137137e-01,
        -5.91692809e-01, -7.63153690e-01, -2.98090626e-01,
        -3.69328266e-01],
       [-7.70565853e-01,  1.36299902e+00, -2.05323863e-01,
         2.25199068e-01, -1.59304857e+00, -1.43346528e+00,
        -1.36762302e+00,  7.03572403e-01,  8.95723305e-01,
         8.67668200e-01],
       [-9.93000515e-01,  2.72357507e-01,  3.23712139e-01,
        -3.82233608e-01,  5.34369752e-01, -8.44199920e-01,
         5.42852767e-01,  8.17272797e-01, -1.72533952e-01,
        -8.

In [61]:
a[0]            #first row called.

array([ 0.44202864, -0.52780447, -0.003064  ,  0.78057585, -0.31154934,
        0.51419992, -1.24004498, -0.61540436, -0.92880553,  0.59236394])

In [62]:
a [0][5]    #first row, 5 th column called

0.5141999150527002

In [65]:
a[1:10:2]               #1 = 1st row, 10= 10th column, step=2

array([[-1.09038052,  1.87959939, -0.7674727 ,  0.61514973, -0.31786393,
         0.06274471, -0.04550606, -0.36420618,  0.96697788, -0.47823227],
       [-0.77056585,  1.36299902, -0.20532386,  0.22519907, -1.59304857,
        -1.43346528, -1.36762302,  0.7035724 ,  0.89572331,  0.8676682 ],
       [ 0.69058293,  0.86551986, -0.06772457,  1.43614779, -0.05594364,
         0.9329901 , -1.21775006,  0.21963248, -0.14173752, -1.16422094],
       [ 0.18056722, -0.59927197, -0.89553112,  0.46563148,  0.58432148,
         1.17983947, -0.89007682, -0.42428209, -0.658421  , -1.97080666],
       [ 1.14924457,  1.81310201, -0.76716015, -0.16653382,  0.2032482 ,
         0.76201379,  0.05312237, -0.4438966 ,  0.0760923 ,  0.54499798]])

In [67]:
a[::,0:4]         #all rows, columns 4

array([[ 4.42028637e-01, -5.27804473e-01, -3.06399957e-03,
         7.80575854e-01],
       [-1.09038052e+00,  1.87959939e+00, -7.67472696e-01,
         6.15149730e-01],
       [ 8.89453723e-01, -1.82821974e+00, -8.43331895e-01,
         1.26001740e+00],
       [-7.70565853e-01,  1.36299902e+00, -2.05323863e-01,
         2.25199068e-01],
       [-9.93000515e-01,  2.72357507e-01,  3.23712139e-01,
        -3.82233608e-01],
       [ 6.90582932e-01,  8.65519860e-01, -6.77245662e-02,
         1.43614779e+00],
       [-2.60931282e-01,  5.48600195e-01, -3.12390488e+00,
        -4.73012950e-01],
       [ 1.80567220e-01, -5.99271972e-01, -8.95531120e-01,
         4.65631481e-01],
       [ 9.80489738e-01,  1.98180474e-01, -2.90730691e-01,
         9.30128170e-01],
       [ 1.14924457e+00,  1.81310201e+00, -7.67160147e-01,
        -1.66533824e-01]])

In [71]:
b = np.ones((5,5))

In [72]:
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [75]:
b[1:-1,1:-1]=0                                   #an array of 5by5 created where all elements = 0 except the corner ones.
b

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])


# NUMPY FUNCTIONS 

In [88]:
x = np.array ([10,9,8,6,11])


In [89]:
np.sqrt(x)                                         #square roots of 'x'

array([3.16227766, 3.        , 2.82842712, 2.44948974, 3.31662479])

In [90]:
np.power (x,2)                                   #square of 'x'

array([100,  81,  64,  36, 121])

In [93]:
y = np.array ([1,3,5,6,7])

In [95]:
np.maximum(x,y)                           #max from both arrays passed. x max = 10, y max = 7, so 10 given and so on.

array([10,  9,  8,  6, 11])

# np.where

In [96]:
# Ternary operators where you first specify conditiion, if found True 1st expression will be selected and  2st value is
# specified only when 1st is false.
#  Ternary operator applies on whole array.


In [ ]:
#  In data, where values not disclosed or zero given canbe replaced by some value of statement 'N/A' 'Not 'Ok' or etc
#  "where" is used for this.

In [97]:
salary = np.array ([0, -1, 100000, 350000])
salary

array([     0,     -1, 100000, 350000])

In [98]:
 np.where (salary <= 0, 25000,salary)               #on places of vacancy or value <0, 25k assigned.

array([ 25000,  25000, 100000, 350000])

In [100]:
np.where(salary<=0, 'Not Ok',salary)

array(['Not Ok', 'Not Ok', '100000', '350000'], dtype='<U21')

# Mathematical and Statistical Methods

In [121]:
import numpy as np

In [122]:
a= np.array([10,9,8,7,8,10])
a

array([10,  9,  8,  7,  8, 10])

In [123]:
a.mean()                                                   #for mean.

8.666666666666666

In [124]:
a.cumsum()                            #cumulative sum of a.

array([10, 19, 27, 34, 42, 52])

In [125]:
a.cumprod()                             #cumulative product.

array([    10,     90,    720,   5040,  40320, 403200])

In [126]:
b = a>5
b

array([ True,  True,  True,  True,  True,  True])

In [127]:
b.sum()

6

In [128]:
b.any()             #if any true.

True

In [129]:
b.all()                #if all true.

True

In [134]:
a.sort()
a

array([ 7,  8,  8,  9, 10, 10])

In [136]:
np.unique(a)                              #unique elements.

array([ 7,  8,  9, 10])

# File Input Output

In [137]:
# Numpy benefit ====> nall arrays can be saved here. 
# not only individual arrays saved but many can be + uploaded.

In [138]:
#  np.save() =====> to save a file
#  np.savez ======> to save many files.


In [142]:
a =[1,2,3,4, 5]
a

[1, 2, 3, 4, 5]

In [144]:
b = [10,20,30,40,50,60]
b

[10, 20, 30, 40, 50, 60]

In [148]:
np.save('texta',a)

In [150]:
loada= np.load('texta.npy')

In [151]:
loada                                                #loaded

array([1, 2, 3, 4, 5])

In [152]:
np.savez ("textab", a,b)

In [156]:
loadab= np.load("textab.npz")                      #2files saved+ loaded
loadab

# Linear ALgebra Operations 

In [157]:
#  since numpy = complete pkg, linear algebra also available.

In [158]:
"""diag===> Return the diagonal (or off-diagonal) elements of a square matrix as a 1D array, or convert a 1D array into a square
matrix with zeros on the off-diagonal
dot===> Matrix multiplication
trace====> Compute the sum of the diagonal elements
det===> Compute the matrix determinant
eig===> Compute the eigenvalues and eigenvectors of a square matrix
inv===> Compute the inverse of a square matrix
pinv===> Compute the Moore-Penrose pseudo-inverse inverse of a square matrix
qr===> Compute the QR decomposition
svd===> Compute the singular value decomposition (SVD)
solve===> Solve the linear system Ax = b for x, where A is a square matrix
lstsq===> Compute the least-squares solution to y = Xb"""

'diag===> Return the diagonal (or off-diagonal) elements of a square matrix as a 1D array, or convert a 1D array into a square\nmatrix with zeros on the off-diagonal\ndot===> Matrix multiplication\ntrace====> Compute the sum of the diagonal elements\ndet===> Compute the matrix determinant\neig===> Compute the eigenvalues and eigenvectors of a square matrix\ninv===> Compute the inverse of a square matrix\npinv===> Compute the Moore-Penrose pseudo-inverse inverse of a square matrix\nqr===> Compute the QR decomposition\nsvd===> Compute the singular value decomposition (SVD)\nsolve===> Solve the linear system Ax = b for x, where A is a square matrix\nlstsq===> Compute the least-squares solution to y = Xb'

In [159]:
#  Row wise concatination ====> axis = 0, vstack  ===> column lenghtens in row wise concatenation
# Column wise concatenation ===> axis 1, hstack ====> row lenthens in column wise concatenation

In [167]:
x = [[1,2,3,4], [6,7,8,9]]
y = [[8,6,5,9],[7,8,9,0]]

In [168]:
arr1 = np.array (x)

In [169]:
arr2 = np.array (y)

In [170]:
np.concatenate ((arr1,arr2), axis =0)

array([[1, 2, 3, 4],
       [6, 7, 8, 9],
       [8, 6, 5, 9],
       [7, 8, 9, 0]])

In [171]:
np.concatenate ((arr1,arr2), axis =1)

array([[1, 2, 3, 4, 8, 6, 5, 9],
       [6, 7, 8, 9, 7, 8, 9, 0]])

In [172]:
np.vstack((arr1,arr2))            #row

array([[1, 2, 3, 4],
       [6, 7, 8, 9],
       [8, 6, 5, 9],
       [7, 8, 9, 0]])

array([[1, 2, 3, 4, 8, 6, 5, 9],
       [6, 7, 8, 9, 7, 8, 9, 0]])