In [1]:
# import libraries before working on it.


In [2]:
import numpy as np

In [3]:
arrId = np.array([444,55,66,77])
arrId


array([444,  55,  66,  77])

In [4]:
arrId[2]   # index given in order to retrack any value.

66

In [7]:
#slicing- for range of numbers
arrId[1:3]  #slicing works with one value less, i.e if with 55, 66 is also required, provide index of next number.


array([55, 66])

In [8]:
arrId

array([444,  55,  66,  77])

In [9]:
arr2d = np.array ([[22,33,44],[55,66,77],[88,99,]])
arr2d

array([list([22, 33, 44]), list([55, 66, 77]), list([88, 99])],
      dtype=object)

In [10]:
arr2d[:2]

array([list([22, 33, 44]), list([55, 66, 77])], dtype=object)

In [12]:
arr3d=np.array([[[100,200,300],[400,500,600],[700,800,900]]])   #format for 3D [[[]]] i.e 3 sq brackets.
arr3d

array([[[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [15]:
arr3d.shape   #s i.e 3D= 3rows 3 cloumn

(1, 3, 3)

In [17]:
arr3d.ndim  #for dimensions

3

In [18]:
arr3d

array([[[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [19]:
arr3d[2]  #first index always reads on 2D

IndexError: index 2 is out of bounds for axis 0 with size 1

In [20]:
arr3d.shape  #1 from output tells the numbers of 2Ds in 1, 3 tells the numbers of rows available, next3 tells the num of column

(1, 3, 3)

In [21]:
arr3d

array([[[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [30]:
arr3d=np.array([[[100,200,300],[400,500,600],[700,800,900],[1,2,3],[4,5,6],[7,8,9]]])
arr3d

array([[[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900],
        [  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]]])

In [32]:
#in order to retrack 2ndline from above given:
arr3d[0][1]

array([400, 500, 600])

In [34]:
arr3d[0][4]

array([4, 5, 6])

In [37]:
arr3d[1:2:]

array([], shape=(0, 6, 3), dtype=int32)