In [1]:
import numpy as np

In [3]:
arr2d =np.array([[[2,4,6,8,10],[1,2,3,4,5],[4,0,6,2,5],[6,6,1,5,3],[7,5,1,6,5],[8,2,4,9,7]]])
arr2d

array([[[ 2,  4,  6,  8, 10],
        [ 1,  2,  3,  4,  5],
        [ 4,  0,  6,  2,  5],
        [ 6,  6,  1,  5,  3],
        [ 7,  5,  1,  6,  5],
        [ 8,  2,  4,  9,  7]]])

In [5]:
arr2d.shape
arr2d.ndim

3

In [10]:
arr = np.arange(36).reshape(6,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [11]:
arr.ndim

2

In [12]:
arr.shape

(6, 6)

In [19]:
arr[2][3:6]

array([15, 16, 17])

In [22]:
arr[3][:3]

array([18, 19, 20])

In [24]:
#if row12 to17 values req
#while sclicing 2D, rows and column provided to array.
#all elements are >>columns

In [29]:
arr[4:5]   #arr[row,column]

array([[24, 25, 26, 27, 28, 29]])

In [30]:
arr[2:3:]  #other way

array([[12, 13, 14, 15, 16, 17]])

In [31]:
arr[2:3,]   #other method

array([[12, 13, 14, 15, 16, 17]])

In [34]:
arr[ ,2] #all rows and 2nd column


SyntaxError: invalid syntax (<ipython-input-34-240f19235754>, line 1)

In [35]:
arr        #slice from 7 to 29, as per directed.

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [40]:
arr[1:5]

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [45]:
arr [2:4,5]  #2 index for 17, 3index for 23 but it's a slice so next index given, i.e 4, 5 coz index to last column =5

array([17, 23])

In [47]:
arr[3:5,0]

array([18, 24])

In [48]:
arr[4:5,3]

array([27])

In [51]:
arr[:,::2]  #allrows and all columns,,, ::= for steps i.e alternate columns given.

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28],
       [30, 32, 34]])

In [52]:
#if steps to be given in rows
arr[::2,::2]

array([[ 0,  2,  4],
       [12, 14, 16],
       [24, 26, 28]])

In [54]:
arr[:5:2,::2]  #start of row, end of row, step of column

array([[ 0,  2,  4],
       [12, 14, 16],
       [24, 26, 28]])

In [55]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

# BOOLEAN INDEXING

true and false, when data fetched not by indexing but by T/F, boolean indexing done

In [17]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
names

#numpy has no strings hence in output shown as string but are not kept string therefore the data type is weird.

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [18]:
data = np.random.randn(7,4)  #data= 2D


In [19]:
names == 'Bob'   #in array, eherever the value "Bob" is present = True

array([ True, False, False,  True, False, False, False])

In [20]:
data>1  #without data frame i.e only query given> and = T/F

array([[False, False, False, False],
       [False, False, False,  True],
       [False, False, False,  True],
       [ True, False,  True, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [21]:
data[data>1]   #For exact values fetched, data>1 kept in data frame

array([2.18898091, 1.80013058, 1.3696402 , 1.04738636, 1.52390827,
       2.10252291])

In [22]:
data[names=='Bob']

array([[-1.21553231,  0.77246676, -2.17329162,  0.31850924],
       [ 1.3696402 ,  0.10803905,  1.04738636,  0.08876608]])

In [23]:
data = np.random.randn(7,4)
data

array([[-0.30215513, -1.26856205,  1.59582103,  1.22286737],
       [-0.01569934,  1.60701922, -0.17108883,  1.51344017],
       [-0.62599325,  0.84334354,  1.06157188,  0.63231209],
       [-0.77802052,  1.57382181, -0.50330397, -0.74951089],
       [-0.61287959, -0.86335084, -0.17749652, -0.29674169],
       [ 0.02851086, -0.46416084, -0.25022228, -2.08457971],
       [-0.96302966,  0.03627315,  0.16256512, -1.7728231 ]])

In [24]:
data[True,True,False,True,True,False,False]  #output weird hence data made boolean below.

array([], shape=(0, 7, 4), dtype=float64)

In [25]:
bol = np.array([True,True,False,True,True,False,False],dtype="bool")
data[bol]

array([[-0.30215513, -1.26856205,  1.59582103,  1.22286737],
       [-0.01569934,  1.60701922, -0.17108883,  1.51344017],
       [-0.77802052,  1.57382181, -0.50330397, -0.74951089],
       [-0.61287959, -0.86335084, -0.17749652, -0.29674169]])

In [26]:
import numpy as np

In [27]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [28]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [29]:
cond = names != 'Bob'

In [30]:
data[~cond]

array([[-0.30215513, -1.26856205,  1.59582103,  1.22286737],
       [-0.77802052,  1.57382181, -0.50330397, -0.74951089]])

In [32]:
data

array([[-0.30215513, -1.26856205,  1.59582103,  1.22286737],
       [-0.01569934,  1.60701922, -0.17108883,  1.51344017],
       [-0.62599325,  0.84334354,  1.06157188,  0.63231209],
       [-0.77802052,  1.57382181, -0.50330397, -0.74951089],
       [-0.61287959, -0.86335084, -0.17749652, -0.29674169],
       [ 0.02851086, -0.46416084, -0.25022228, -2.08457971],
       [-0.96302966,  0.03627315,  0.16256512, -1.7728231 ]])

In [33]:
data[5][2]

-0.2502222765521186

In [37]:
#cond = names != "Bob"
data[cond,1:3]


array([[ 1.60701922, -0.17108883],
       [ 0.84334354,  1.06157188],
       [-0.86335084, -0.17749652],
       [-0.46416084, -0.25022228],
       [ 0.03627315,  0.16256512]])

In [41]:
#cond = names != "Bob"
data = np.arange(28).reshape(7,4)
print(data)
print(cond)
data[cond,1:3]
#0 to27, data printed,, condition T/F printed,, data[cond,1:3] pick complete rows then  come to 3rd column 
#hence complete data not printed
#first line= false hence not printed, 2nd= T > printed, 3rd = T> printed

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
[False  True  True False  True  True  True]


array([[ 5,  6],
       [ 9, 10],
       [17, 18],
       [21, 22],
       [25, 26]])

In [44]:
# on numpy, for and>>> "&" used
cond = (names =="Bob") & (names=="joe")
cond
#all = false coz no two names were mentioned together.

array([False, False, False, False, False, False, False])

In [47]:
cond = (names == "Bob") |  (names=="Joe")              # | used for 'or', & used for 'and'
cond


array([ True,  True, False,  True, False,  True,  True])

# FANCY INDEXING

If a matrix is to be made with self choice of numbers

In [49]:
#empty >>> garbage values fetched
arr = np.empty((8, 4))

for i in range(8):
    arr[i]= i

In [60]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [61]:
arr[[1,2,3]]   #values within first[] = rows

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [62]:
arr [[4,0,1,7]] #if one wants 4th row to be placed on 1st so mention 4 on 1st place, 0 row to be given in 2nd's place and so on.

array([[4., 4., 4., 4.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [7., 7., 7., 7.]])

In [63]:
arr[[4,0,1,2],[2,3,0,1]]  #here within one [], there are 2 given. One for row other for column.

array([4., 0., 1., 2.])

In [67]:
arr = np.arange(32).reshape(8,4)
print(arr)

arr[[1,5,7,2]][:,[0.,3,1,2]]
#1[0,3,1,2],5[0,3,1,2],7[0,3,1,2],2[0,3,1,2]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [69]:
arr.T #>>>>>>>>>> .T= transposed or transpose()
#transposed == verticle changed into horizontal i.e rows made column vice versa.

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [70]:
#3D can also be transposed.

In [71]:
#.modf >>> whole part and decimal/ remainder part separated.
#4.3 skipped

In [72]:
#.mean >> for mean
#.sum>>> for sum
#.cumsum>> commulative sum
# Standard deviation = how far the data ppoint form mean data.
#  say num of values =10,  mean = 5, how less/more the mean is from original value = deviation
# .any() >>> if any value= true, true returned
# .all() >> if any value = false, false returned.
# .sort() >> sorts
#  set() >> picks unique items or deletes repeated values.
#np.save() >> saves array on root file
# np.load() >> to get saved array
#  inv()  >> for inverse of matrix


In [73]:
# Appendix A has advanced numpy.  pg457

# CONCATENATION

In [74]:
# reshaped>> C order> rows play major part, F order> columns play major part. c order> advanced.
#  arrays can be concatinated vertically + horizontally.
# whenever matrix is + on 0 axis >> num of rows increase.
# axis 0 = x axis> when + on axis zero, number of rows increased.
# whenever matrix is + on 1 axis >> number of columns increased
#  pratically, it is assumed that any value + on 0 axis will end up increasing the size of horizontal row but actually the
# increase of number of rows i.e the increase of leangth of a column is the output of the number of values + on 0axis.


In [75]:
# np.stack >> two arrays kept on one another, whereas in concatenation two arrays after concatenation became one.
#  np.vsplit() in vplit > you gotta provide certain number say 3 to let it split in 3 parts.
# in np.vsplit >>>>> horizontally sliced eventhough v refers to vertical.
#  in np.hsplit >>. vertically sliced

In [81]:
arr = np.arange (36).reshape(6,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [82]:
arr.hsplit(arr, 3)

AttributeError: 'numpy.ndarray' object has no attribute 'hsplit'